#include <webpage.h>
#include <ekf.h> //for getting debug data
#include <mqtt.h> //for flags, dataframe struct and message formatting

float debug_Heading = 0;
float debug_Lat = 0;
float debug_Lon = 0;

//Embedded file labels are generated by the build system based on filenames*/
extern const uint8_t coordinates_html_start[] asm("_binary_coordinates_html_start");
extern const uint8_t coordinates_html_end[]   asm("_binary_coordinates_html_end");

extern const uint8_t coordinates_js_start[]  asm("_binary_coordinates_js_start");
extern const uint8_t coordinates_js_end[]    asm("_binary_coordinates_js_end");

//Struct and event handler for html
static esp_err_t html_get_handler(httpd_req_t *req){
    const size_t size = (coordinates_html_end - coordinates_html_start);
    httpd_resp_set_type(req, "text/html");
    
    //Send the response. HTTPD_RESP_USE_STRLEN tells the server to calculate the length automatically.
    esp_err_t error = httpd_resp_send(req, (const char *)coordinates_html_start, size);
    
    if(error != ESP_OK){
        printf("[HTTP_Status] Failed to send HTML response!");
    }
    return error;
}
static const httpd_uri_t html_uri = {
    .uri       = "/",                   
    .method    = HTTP_GET,            
    .handler   = html_get_handler                 
};

//Struct and event handler for javascript
static esp_err_t js_get_handler(httpd_req_t *req){
    const size_t size = (coordinates_js_end - coordinates_js_start);
    httpd_resp_set_type(req, "text/javascript");
    return httpd_resp_send(req, (const char *)coordinates_js_start, size);
}

static const httpd_uri_t js_uri = {
    .uri       = "/coordinates.js", //what the html will ask for
    .method    = HTTP_GET,
    .handler   = js_get_handler    
};

static esp_err_t send_status_handler(httpd_req_t *req){
    char status = '0';
    if(!GPS_Fixed){
        status = '1';
    }
    else if(MPU6050_is_Calibrating || HMC5883_is_Calibrating){
        status = '2';
    }
    httpd_resp_set_type(req, "text/plain");
    return httpd_resp_send(req, (const char *)&status, 1);
}

static const httpd_uri_t status_get_uri = {
    .uri       = "/get_status", //what the script will ask for
    .method    = HTTP_GET,
    .handler   = send_status_handler    
};

//Struct and event handler for updating the page
static esp_err_t send_data_handler(httpd_req_t *req){
    char message[256] = {0};
    if(!DataFrame_2_JSON(message, sizeof(message), Global_Data)){
        return ESP_FAIL;
    }
    httpd_resp_set_type(req, "application/json");
    return httpd_resp_send(req, (const char *)message, strlen(message));
}

static const httpd_uri_t data_get_uri = {
    .uri       = "/get_data", //what the script will ask for
    .method    = HTTP_GET,
    .handler   = send_data_handler    
};

//Struct and event handler for updating the page
static esp_err_t send_debug_handler(httpd_req_t *req){
    char message[256] = {0};
    float roll, pitch, vel_n, vel_e, pos_n, pos_e;
    roll = pitch = vel_n = vel_e = pos_n = pos_e = 0;
    get_tilt(&roll, &pitch);
    get_vel(&vel_n, &vel_e);
    get_NE_pos(&pos_n, &pos_e);
    snprintf(message, sizeof(message), "{"
                                        "\"Roll\": %.6f, "
                                        "\"Pitch\": %.6f, "
                                        "\"Heading_Raw\": %.6f, "
                                        "\"Vel_N\": %.6f, "
                                        "\"Vel_E\": %.6f, "
                                        "\"Pos_N\": %.6f, "
                                        "\"Pos_E\": %.6f, "
                                        "\"Lat_Raw\": %.6f, "
                                        "\"Lon_Raw\": %.6f "
                                        "}", 
                                        roll, 
                                        pitch, 
                                        debug_Heading, 
                                        vel_n, 
                                        vel_e, 
                                        pos_n, 
                                        pos_e, 
                                        debug_Lat, 
                                        debug_Lon);
    httpd_resp_set_type(req, "application/json");
    return httpd_resp_send(req, (const char *)message, strlen(message));
}

static const httpd_uri_t debug_get_uri = {
    .uri       = "/get_debug", //what the script will ask for
    .method    = HTTP_GET,
    .handler   = send_debug_handler    
};

static httpd_handle_t HTTP_start(){
    httpd_handle_t server = NULL;
    httpd_config_t server_config = HTTPD_DEFAULT_CONFIG();
    server_config.lru_purge_enable = true; //allow the http server to close the socket if needed (least recently used_purge_enable)

    debug_printf("[HTTP_Status] Starting server on port: '%d'", server_config.server_port);
    if(httpd_start(&server, &server_config) == ESP_OK){
        // Set URI handlers
        debug_printf("[HTTP_Status] Registering URI handlers");
        httpd_register_uri_handler(server, &html_uri);
        httpd_register_uri_handler(server, &js_uri);
        httpd_register_uri_handler(server, &data_get_uri);
        httpd_register_uri_handler(server, &debug_get_uri);
        httpd_register_uri_handler(server, &status_get_uri);
        return server;
    }

    printf("[HTTP_Status] Error starting server!");
    return NULL;
}

///////////////////////////////////////////////////////////////////////
///////////////////////// Main Functions //////////////////////////////
///////////////////////////////////////////////////////////////////////

void TaskWebpage(void *pvParameters){
    printf("======= Webserver function started =======\r\n");
    
    while(!WiFi_Connected) delay(1000); //wait for wifi to connect
    httpd_handle_t http_server = HTTP_start(); //then start http server

    while(http_server){
        delay(1000);
    }
}

